__title__ = "terraplen"
__description__ = "Easy and Useful Amazon Scraper"
__url__ = "https://github.com/nagataaaas/terraplen"
__version_info__ = ("0", "1", "0")
__version__ = ".".join(__version_info__)
__author__ = "Yamato Nagata"
__author_email__ = "chickenwingswillfly@gmail.com"
__maintainer__ = "Yamato Nagata"
__license__ = "MIT"
__copyright__ = "(c) 2021 by Yamato Nagata"
